<?php

namespace ContainerOVIUfTP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LoginController' shared autowired service.
     *
     * @return \App\Controller\LoginController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/LoginController.php';
        include_once \dirname(__DIR__, 4).'/src/Login/LoginUseCase.php';

        return $container->services['App\\Controller\\LoginController'] = new \App\Controller\LoginController(new \App\Login\LoginUseCase(($container->privates['App\\Repository\\User\\UserRepository'] ?? $container->load('getUserRepositoryService'))));
    }
}
