<?php

namespace ContainerOVIUfTP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyChallengePhoneControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VerifyChallengePhoneController' shared autowired service.
     *
     * @return \App\Controller\VerifyChallengePhoneController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/VerifyChallengePhoneController.php';

        return $container->services['App\\Controller\\VerifyChallengePhoneController'] = new \App\Controller\VerifyChallengePhoneController(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
