version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: makeitshine
    ports:
      - "5432:5432"
  redis-server:
    container_name: redis
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    depends_on:
      - db
