<?php

namespace ContainerKP0OpIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckEmailControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CheckEmailController' shared autowired service.
     *
     * @return \App\Controller\CheckEmailController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/CheckEmailController.php';
        include_once \dirname(__DIR__, 4).'/src/CheckEmail/CheckEmailUseCase.php';

        return $container->services['App\\Controller\\CheckEmailController'] = new \App\Controller\CheckEmailController(new \App\CheckEmail\CheckEmailUseCase(($container->privates['App\\Repository\\User\\UserRepository'] ?? $container->load('getUserRepositoryService'))));
    }
}
