<?php

namespace ContainerKP0OpIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignUpControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SignUpController' shared autowired service.
     *
     * @return \App\Controller\SignUpController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/SignUpController.php';
        include_once \dirname(__DIR__, 4).'/src/SignUp/SignUpUseCase.php';

        return $container->services['App\\Controller\\SignUpController'] = new \App\Controller\SignUpController(new \App\SignUp\SignUpUseCase(($container->privates['App\\Repository\\User\\UserRepository'] ?? $container->load('getUserRepositoryService'))));
    }
}
