<?php

namespace ContainerKP0OpIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyChallengeEmailControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VerifyChallengeEmailController' shared autowired service.
     *
     * @return \App\Controller\VerifyChallengeEmailController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/VerifyChallengeEmailController.php';

        return $container->services['App\\Controller\\VerifyChallengeEmailController'] = new \App\Controller\VerifyChallengeEmailController(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
