<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKP0OpIr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKP0OpIr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKP0OpIr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKP0OpIr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKP0OpIr\App_KernelDevDebugContainer([
    'container.build_hash' => 'KP0OpIr',
    'container.build_id' => 'f376b61a',
    'container.build_time' => 1733751740,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKP0OpIr');
