<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'AnalyseImage' => [[], ['_controller' => 'App\\Controller\\AnalyseImageController::analyseImage'], [], [['text', '/AnalyseImage']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'HealthCheck' => [[], ['_controller' => ['App\\Controller\\HealthController', 'health']], [], [['text', '/Health']], [], [], []],
    'analyseImage' => [[], ['_controller' => ['App\\Controller\\AnalyseImageController', 'AnalyseImage']], [], [['text', '/AnalyseImage']], [], [], []],
    'SendChallengePhone' => [[], ['_controller' => ['App\\Controller\\SendChallengePhoneController', 'SendChallengePhone']], [], [['text', '/SendChallengePhone']], [], [], []],
    'SendChallengeEmail' => [[], ['_controller' => ['App\\Controller\\SendChallengeEmailController', 'SendChallengeEmail']], [], [['text', '/SendChallengeEmail']], [], [], []],
    'VerifyChallengePhone' => [[], ['_controller' => ['App\\Controller\\VerifyChallengePhoneController', 'VerifyChallengePhone']], [], [['text', '/VerifyChallengePhone']], [], [], []],
    'VerifyChallengeEmail' => [[], ['_controller' => ['App\\Controller\\VerifyChallengeEmailController', 'VerifyChallengeEmail']], [], [['text', '/VerifyChallengeEmail']], [], [], []],
    'SignUp' => [[], ['_controller' => ['App\\Controller\\SignUpController', 'SignUp']], [], [['text', '/SignUp']], [], [], []],
    'CheckEmail' => [[], ['_controller' => ['App\\Controller\\CheckEmailController', 'CheckEmail']], [], [['text', '/CheckEmail']], [], [], []],
    'Login' => [[], ['_controller' => ['App\\Controller\\LoginController', 'Login']], [], [['text', '/Login']], [], [], []],
    'App\Controller\AnalyseImageController::analyseImage' => [[], ['_controller' => 'App\\Controller\\AnalyseImageController::analyseImage'], [], [['text', '/AnalyseImage']], [], [], []],
    'App\Controller\CheckEmailController::checkEmail' => [[], ['_controller' => ['App\\Controller\\CheckEmailController', 'CheckEmail']], [], [['text', '/CheckEmail']], [], [], []],
    'App\Controller\HealthController::health' => [[], ['_controller' => ['App\\Controller\\HealthController', 'health']], [], [['text', '/Health']], [], [], []],
    'App\Controller\LoginController::login' => [[], ['_controller' => ['App\\Controller\\LoginController', 'Login']], [], [['text', '/Login']], [], [], []],
    'App\Controller\SendChallengeEmailController::sendChallengeEmail' => [[], ['_controller' => ['App\\Controller\\SendChallengeEmailController', 'SendChallengeEmail']], [], [['text', '/SendChallengeEmail']], [], [], []],
    'App\Controller\SendChallengePhoneController::sendChallengePhone' => [[], ['_controller' => ['App\\Controller\\SendChallengePhoneController', 'SendChallengePhone']], [], [['text', '/SendChallengePhone']], [], [], []],
    'App\Controller\SignUpController::signUp' => [[], ['_controller' => ['App\\Controller\\SignUpController', 'SignUp']], [], [['text', '/SignUp']], [], [], []],
];
