FROM php:8.2-apache


RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip

COPY --from=composer/composer:latest-bin /composer /usr/bin/composer

RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony*/bin/symfony /usr/local/bin/symfony


COPY . .


RUN composer install

EXPOSE 8000

CMD ["symfony", "server:start", "--no-tls", "--port=8000"]