name: pull_request before merging

on:
  pull_request:

defaults:
  run:
    working-directory: ./apps/api

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php bin/phpunit
